#!/bin/bash

RUN_DIR=/var/vcap/sys/run/gerrit
LOG_DIR=/var/vcap/sys/log/gerrit
CONFIG_DIR=/var/vcap/jobs/gerrit/config
PIDFILE=${RUN_DIR}/pid
RUN_AS=vcap
GERRIT=/var/vcap/packages/gerrit

export JAVA_HOME=/var/vcap/packages/oracle-java-jdk
export PATH=$JAVA_HOME/bin:$PATH

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUN_AS:$RUN_AS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    java -jar ${GERRIT}/gerrit*.war init --batch -d ${CONFIG_DIR} \
      >>  $LOG_DIR/gerrit.stdout.log \
      2>> $LOG_DIR/gerrit.stderr.log
    ;;

  stop)
    kill -9 `cat $PIDFILE` && rm -f $PIDFILE
    ;;

  *)
  echo "Usage:ctl {start|stop}" ;;
esac
